### PR TITLE
Reset trigger from error state

### PR DESCRIPTION
**Pull request by romantitov**
Since there were some[ important bug fixes](https://github.com/quartznet/quartznet/releases) provided in Quartz

- [X] Updated Quartz packages to ver. 3.6.2
- [X] Implemented ResetTriggerFromErrorState (related to the [PR 1904](https://github.com/quartznet/quartznet/pull/1904))
- [ ] Regrettably, I couldn't devise a test for the new method as the integration test scheduler lacks a straightforward means to generate a trigger with an "Error" state.
- [ ] CosmosDB nuget package was not updated since the latest version (I've tested v3.32.1) works unstable.

### CODE REVIEW

**Comment by frantisekjandos** [comment]
Hi, I am OK to merge it now, but according to checkboxes do you also plan to do the unchecked ones? ;-) Upgrade of CosmosDB library is very welcome.

**Comment by romantitov** [comment]
Hi @frantisekjandos I would suggest not upgrading CosmosDB to the latest version (at the moment v3.32.1) since it works not so stable as currently used 3.17.1 (you can check it with tests in the repository). Probably in future versions, the package will be more stable, and the upgrade will make sense.

Regarding another checkbox, I just wanted to highlight that I didn't find a good way to cover ResetTriggerFromErrorState by any tests, but if you know how to set Error state for a trigger during a test, I would be happy to create some tests.

**Comment by romantitov** [comment]
Hi @frantisekjandos any plans to complete the PR and update nuget?

**Comment by frantisekjandos** [comment]
New NuGet version has been released, thank you for the contribution.

**Pull request merged**
